### PR TITLE
fix: move away from mjs extension to work in more environments

### PR DESCRIPTION
**Pull request by AhmedAymanM**
## Summary

moved away from using `.mjs` files extension for es-modules as it seems that there are some compatibility issues with It 

## Test plan

This code doesn't change any functionality, I ran the tests, and they all pass.

### CODE REVIEW

**Comment by snaer-yolabs** [comment]
Nice work man! Hoping this goes out soon

**Comment by snaer-yolabs** [comment]
This should fix this issue
https://github.com/gregberge/xstyled/issues/264

**Comment by AhmedAymanM** [comment]
did you test it locally? @snaer-yolabs 
I tested it with storybook and it fixed the issue for me.
I didn't try it with next.js or other tools though but I believe it should work nonetheless.

**Comment by snaer-yolabs** [comment]
No I did not test it locally @AhmedAymanM

**Comment by electroheadfx** [comment]
I have the same error under ViteJS/React install : http://host.electroheadfx.fr/efxbox/laurent/Capturedecran2021-06-19a18.34.32.png I have not any issue with styled-components, chakra-ui (so styled-system) packages with VITE

**Pull request merged**
