### PR TITLE
feat: add support for margin-inline-start and margin-inline-end

### PR DESCRIPTION
**Pull request by ivoilic**
## Summary
Adds support for `margin-inline-start` and `margin-inline-end` via `ms` and `me`

## Test plan
Corresponding tests added

### CODE REVIEW

**Comment by agriffis** [comment]
I learned some CSS from this PR :student: 

Should we worry about accumulating lots of abbreviated props? Should there be a way for projects to opt in to abbreviations, or even to specify their own, or omit defaults that are problematic? This question isn't specific to this PR, it just makes me wonder about it.

Otherwise this LGTM, although all the extra typings for states highlight the importance of #206.

**Comment by gregberge** [comment]
> Should we worry about accumulating lots of abbreviated props? Should there be a way for projects to opt in to abbreviations, or even to specify their own, or omit defaults that are problematic? This question isn't specific to this PR, it just makes me wonder about it.

I think the shortcut is not necessary, this prop represent and advanced usage. I think it is good to support it but for the prefix it is too confusing for me.

**Review by gregberge — CHANGES_REQUESTED** [review]
Thanks for this addition, I also learn CSS from this this PR. Could you please remove the prefix, too generic I am sorry.. There is also `marginBlockStart` and `marginBlockEnd` so it can't be just `me` and `ms`.

**Comment by gregberge** [comment]
It will not be part of xstyled, perhaps in an official i18n plugin. For now you should add the utility by yourself, the v3 let you do it easily https://xstyled.dev/docs/adding-new-utilities/.

**Pull request closed without merging**
