### PR TITLE
Feat/react native

### PR DESCRIPTION
**Pull request by diegotsi**
## Summary
Hi! as everyone should know this lib does not work with react-native since version 1.12.0, we can see more details about this on #123 and #13 .

I already [started a package](https://github.com/gregberge/xstyled/pull/140) for react-native on version 1x , but now i'm started this one based on v3.

We are using version 1.11.0 on our apps and works pretty well, and after investigating the problem i figured out that the main problem is because createGlobalStyle does not work on react native. We can check more info about this here.

So I created a new package called styled-components-native. 

Version 3x has a lot of great features for react web, but maybe not all of them works with react-native, so the main goal of this PR is to start with the basic things that already help us a lot in react native, like Theme, Utility Props, System and the Magic Styled Components.

Why create a new package? It's basically to separate responsibilities and does not limit the web package because of react-native, with a new package we can also use styled-components/native instead of styled-components.

Things that I've done:

- [x] Copy Styled Components Package and cleanup RN incompatible features.
- [X] Test the new version on react native app

## Test plan

That's the code I use for the test with react-native:

```javascript
import styled from '@xstyled/styled-components';

const WrapView = styled(View)`
  width: 200px;
  height: 200px;
  background-color: red;
`;
```

Before the changes:

Screen Shot 2021-06-03 at 09 04 22

After the changes:

### CODE REVIEW

**Comment by kamalbennani** [comment]
@gregberge Any news regarding future support of React-native?

**Comment by gregberge** [comment]
@kamalbennani ask @diegotsi, I am not a React Native user, so I can't work on it.

**Comment by diegotsi** [comment]
Hi @kamalbennani, I'm planning to finish this by the end of next week.

**Comment by eugeneross** [comment]
@diegotsi Looking forward to seeing this. Is the plan to have this be compatible with both v1 and v2? Or just one?

**Comment by gregberge** [comment]
Looks like it will never happen, I close it.

**Pull request closed without merging**
