### PR TITLE
feat: added compatibility with react native

### PR DESCRIPTION
**Pull request by diegotsi**
## Summary

Hi! as everyone should know this lib does not work with react-native since version `1.12.0`, we can see more details about this on #123 and #13 . 

## Test plan

But we are using version `1.11.0` on our apps and works pretty well, and after investigating the problem i figured out that the main problem is because `createGlobalStyle` does not work on react native. We can check more info about this [here](https://styled-components.com/docs/api#createglobalstyle).

So I created a new package called `react-native` that uses everything that `@xstyled/styled-components` can offer except the features depends on `createGlobalStyle`. 

Why create a new package? It's basically to separate responsibilities and does not limit the web package because of react-native, with a new package we can also use `styled-components/native` instead of `styled-components`.

I tested this package on our app and it's working pretty well, but the objective of this PR is to create a discussion. 

Does this package make sense?

### CODE REVIEW

**Comment by felipefialho** [comment]
Hi @diegotsi, I think that is a good idea separate the responsibilities. We know that ReactNative have some differences about the normal web approach and create a specific package to it, will help us to improve this project without trade off about different technologies.

I like this proposal 😁

**Comment by gregberge** [comment]
Hey @diegotsi, thanks for being involved in this! I think it is a good idea to create a separated package, however the name of the package is not correct. It should be `@xstyled/styled-components-native`. For the content of the package, I trust you. I don't use React Native, so you will be owner on this part. @diegotsi do you want to be maintainer?

**Comment by diegotsi** [comment]
> Hey @diegotsi, thanks for being involved in this! I think it is a good idea to create a separated package, however the name of the package is not correct. It should be `@xstyled/styled-components-native`. For the content of the package, I trust you. I don't use React Native, so you will be owner on this part. @diegotsi do you want to be maintainer?

Yes! I agree with the name `styled-components-native`. And of course, I would like to be a maintainer. I will update this PR with the package name, add tests, etc...

**Comment by gregberge** [comment]
> Yes! I agree with the name `styled-components-native`. And of course, I would like to be a maintainer. I will update this PR with the package name, add tests, etc...

Very good news! Feel free to DM me on Twitter to talk about it!

**Comment by diegotsi** [comment]
> > Yes! I agree with the name `styled-components-native`. And of course, I would like to be a maintainer. I will update this PR with the package name, add tests, etc...
> 
> Very good news! Feel free to DM me on Twitter to talk about it!

I sent you a message!

**Comment by gregberge** [comment]
Please open a new PR for v2.

**Pull request closed without merging**
