### PR TITLE
feat: styled.extend

### PR DESCRIPTION
**Pull request by agriffis**
## Summary

For proper pluggability, we need `styled.extend` to complement the existing `x.extend`. See #246 

This is not the API I would like eventually for a unified xstyled creator, but it's still worthwhile and a step in the right direction.

## API details

Add `createStyled` (like `createX`) so that `styled.extend` can call it.

The recently-added `styledWithGenerator` becomes `styled.withGenerator` for styled-components, and `styled(..., {generator})` for emotion, in each case adhering to their existing API without changing function arities.

## Status

This is a work in progress...

- [x] styled-components rough pass
- [x] emotion rough pass
- [x] tests for `styled.extend`
- [ ] types cleanup

### CODE REVIEW

**Comment by agriffis** [comment]
Interesting gotcha, we can extend `styled` one way but not the other, at least not without additional work.

We can do this:

```jsx
const borderInlineWidth = style({
  prop: ['biw', 'borderInlineWidth'],
  css: 'borderInlineWidth',
  themeGet: getSpace,
})

const myStyled = styled.extend(borderInlineWidth)

const Dummy = myStyled`

<Dummy biw={1} /> // border-inline-width: 4px; ✅
```

but we can't do this:

```jsx
const Dummy = myStyled`
  border-inline-width: 1;
`

<Dummy /> // border-inline-width: 1; ❌
```

The reason is that `transform()` refers to the statically-defined `propGetters`.

I added a skipped test for this, for now. To fix it properly, we would need `createPropGetters` and `createTransform` which makes sense in a fully-extensible xstyled, but it's more work than I'd anticipated at this juncture. I may consider that in a separate pull request to keep this one from getting out of hand.

**Comment by agriffis** [comment]
This is otherwise coming together nicely. I just need to review a couple types that got lost along the way.

**Comment by agriffis** [comment]
Tests run clean, but build fails with various TS errors.

```
✸ yarn build
lerna notice cli v4.0.0
lerna notice filter excluding ["@xstyled/website","@xstyled/benchmarks"]
lerna info filter [ '!@xstyled/website', '!@xstyled/benchmarks' ]
lerna info Executing command in 7 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@xstyled/babel-preset-emotion-css-prop' in 3.6s:

lerna info run Ran npm script 'build' in '@xstyled/prop-types' in 3.7s:

lerna info run Ran npm script 'build' in '@xstyled/util' in 3.8s:

lerna info run Ran npm script 'build' in '@xstyled/system' in 4.7s:

lerna info run Ran npm script 'build' in '@xstyled/core' in 3.6s:

lerna ERR! yarn run build exited 1 in '@xstyled/emotion'
lerna ERR! yarn run build stderr:

src/index.ts → dist/index.js, dist/index.mjs...
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#outputexports
The following entry modules are using named and default exports together:
src/index.ts

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created dist/index.js, dist/index.mjs in 106ms

src/index.ts → dist/index.d.ts...
src/styled.ts(4,14): error TS4023: Exported variable 'styled' has or is using name 'CreateXStyled' from external module "/home/aron/src/xstyled/packages/emotion/src/createStyled" but cannot be named.

[!] (plugin dts) Error: Failed to compile. Check the logs above.
src/index.ts
Error: Failed to compile. Check the logs above.
    at error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:5305:30)
    at throwPluginError (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18033:12)
    at Object.error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18659:20)
    at Object.error (/home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18202:38)
    at Object.transform (/home/aron/src/xstyled/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.cjs:1433:26)
    at /home/aron/src/xstyled/node_modules/rollup/dist/shared/rollup.js:18863:25

lerna ERR! yarn run build exited 1 in '@xstyled/emotion'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
```

**Review by gregberge — APPROVED** [review]
It is a good start but I think we should not release it until we have the good API for that. It will be probably for a v3.1.

**Comment by agriffis** [comment]
@gregberge Agreed. The more I work on this, the more it needs to be holistic instead of piecemeal.

Also I need to learn TS better, but it's taking longer than I'd anticipated.

**Comment by gregberge** [comment]
Closed in favor of #262

**Pull request closed without merging**
