### PR TITLE
Improve: emotion createX function typing

### PR DESCRIPTION
**Pull request by marceloadsj**
## Summary

The current @xstyled/emotion/x.d.ts file is broken due to this issue on typescript:
https://github.com/microsoft/TypeScript/issues/27171

https://unpkg.com/@xstyled/emotion@2.1.0/dist/x.d.ts
If you scroll down to very bottom, you fill find a couple of "... 100 more ..." strings

This branch focuses to improve the x.d.ts file in a way that it does not generate that massive type.

Basically, the main type responsible for generating that big d.ts file is JSX.IntrinsicElements.

## Test plan

(Check the .D.TS tab on right panel)

Simple example of the type on v2.1.0: 
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIigUwIYGMYINwChcwCeYycAUgMoAaA0soQM5wC8cA1vRAGbnUB0ASQB2MKMCENg6AKIAbZCGQiGeXMgAekWHHQQJ8dClQxkVFnAAUAShYA+OAG9ccHXobx1ALkfOXcANochHDivLT0DAC6APze7mJCAOZ4LgC+5g6pqi4oMACuUEJw6nipQA

Example of the changes that this branch suggests:
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAIigUwIYGMYINwChcwCeYycAUgMoAaA0soQM5wC8cA1vRAGbnUB0ASQB2MKMCENg6AKIAbZCGQiGeAsVJUWcAN644cANodCccb1r0GAXQD8ALjgNR4gOZ4AvvmQAPSLDjoEBLw6CioMMiarAAUAJQsAHw6egFBTnDeDlE67qr6KDAArlBCGR5AA

I encourage you to build it local and check the x.d.ts file generated from @xstyled/emotion. Check that, with this new type, the autocomplete still works like it should, for example, showing all html tags when you type `x.`.

image

### CODE REVIEW

**Comment by marceloadsj** [comment]
This is related to the build problem describe in: https://github.com/gregberge/xstyled/issues/172

**Comment by marceloadsj** [comment]
PS: feel free to give your thoughts, concerns, requests etc... on those PRs.
I'm enjoying to use the library and to improve it as much as I can, without deviating from the main focus. :)

**Comment by gregberge** [comment]
@marceloadsj I think it is better like that, even if it is not exact the [TypeScript issue](https://github.com/microsoft/TypeScript/issues/27171) prevent us to do better... So thanks for this fix.

**Comment by marceloadsj** [comment]
Yep! In fact, this https://github.com/microsoft/TypeScript/issues/40354 is an issue more in line with the problem we faced.

It was "solved" from TS side by throwing an error when this ("...and 100 more...") happens.

If the dev usage starts to be slow due to this runtime types, we can improve that by creating a d.ts by hand! :)

**Comment by marceloadsj** [comment]
Yep! In fact, this https://github.com/microsoft/TypeScript/issues/40354 is an issue more in line with the problem we faced.

It was "solved" from TS side by throwing an error when this ("...and 100 more...") happens.

If the dev usage starts to be slow due to this runtime types, we can improve that by creating a d.ts by hand! :)

**Pull request merged**
